# -*- coding: utf-8 -*-
"""Advinhação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRYj0DflA22HhfUg2ojSg_CK8o3LHSyi
"""

#adivinhação
from random import randint

print("--------- Iniciando o Super Game -----------")

tesouro = randint(0,100)
chute = 0
chances = 10

while chute !=tesouro:
  chute = input("Qual o número que você acha que é?")
  if chute.isnumeric():#pergunta se o elemento é numerico
    chute = int(chute)
    chances = chances - 1
    if chute == tesouro:
      print('')
      print('Parabéns! Você acertou')
      print('O numero era {} e você ainda tinha {} chances'.format(tesouro, chances))
      print('')
      break;
    else:
      print('')
      if chute > tesouro:
         print("Você errou! Dica: É um numero menor!")
      else:
         print("Você errou! Dica: É um numero maior!")
      print('Você ainda possui {} chances'.format(chances))#o cormando format joga a informação dentro das chaves
    if chances == 0:
      print('')
      print(f'Suas chances acabaram. O numero era: {tesouro}. Você perdeu')
      print('')
      break;
print("--------Game Over---------")