# -*- coding: utf-8 -*-
"""Calculadora_IR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8pDhamoarolEkrMzP55hSvqKII75vEQ
"""

imposto = 0
def calcular(salario):
  tabela_ir = [
      {"faixa": (0,1903.98), "aliquota": 0,"dedução": 0},
      {"faixa": (1903.99,2826.65), "aliquota": 7.5,"dedução": 142.80},
      {"faixa": (2826.66,3751.05), "aliquota": 15,"dedução": 354.80},
      {"faixa": (3751.06, 4664.68), "aliquota": 22.5,"dedução": 636.13},
      {"faixa": (4664.69, float("inf")), "aliquota": 27.5, "dedução": 869.36}
  ]
  for faixa in tabela_ir:
    if salario > faixa ["faixa"][0] and salario <= faixa["faixa"][1]:
      imposto = (salario * faixa["aliquota"])/100 - faixa["dedução"]
      break;
  return imposto
salario_bruto = float(input("Informe o seu salario bruto:"))#insere o salário bruto
imposto = calcular(salario_bruto)
print(f"O imposto de renda devido é de R${imposto:.2f}")