# -*- coding: utf-8 -*-
"""Calculadora Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ACTFPdwEOBes0vqSxIhKW-YObe8QdaQI
"""

import math
calcular = True
while calcular:
  valor01 = int(input("Insira o primeiro Valor: "))
  valor02 = int(input("Insira o primeiro Valor: "))
  texto = '''
    [1] Soma
    [2] Dividir
    [3] Multiplicar
    [4] Subtrair
    [5] Potencia
    [6] Raiz quadrada
    '''
  print(texto)
  escolha = int(input("Qual operação deseja: "))
  
  if int(escolha) < 0:
    int(escolha)
  else:
    str(escolha)


  if escolha == 1:
    resultado = valor01 + valor02
    print("O resultado da soma é:",resultado)

  if escolha == 2:
    resultado = valor01 / valor02
    print("O resultado da divisão é:",resultado)

  if escolha == 3:
    resultado = valor01 * valor02
    print("O resultado da multiplicação é:",resultado)
  
  if escolha == 4:
    resultado = valor01 - valor02
    print("O resultado da subritação é:",resultado)
  
  if escolha ==5:
    if escolha > 4:
      potencia=1
    for count in range(valor02):
      potencia *= valor01
      count += 1
      print(valor01,"^",valor02,"=",potencia)
  
  if escolha ==6:
    if escolha > 5:
      valor01 = int(input("Entre com um número:\n"))
      raiz = math.sqrt(valor01)
      print(f'\nA raiz quadrada de {valor01} é {raiz}\n')
  
  resultado = input("Você desseja fazer novo cálculo? \nSim ou Não \n")
  if resultado == "nao" or resultado == "não":
    calcular = False